- name: Create kubernetes directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kubernetes/tls
    - /opt/etcd/tls
    - /etc/kubernetes
    - /tmp/kubernetes
    - /etc/systemd/system/kube-apiserver.service.d
    - /etc/systemd/system/kube-controller-manager.service.d
    - /etc/systemd/system/kube-scheduler.service.d

- name: Extract kubernetes package
  unarchive:
    src: "{{ KUBERNETES_PACKAGE }}"
    dest: /tmp/kubernetes
    creates: /tmp/kubernetes/server
    extra_opts: [ "--strip-components=1" ]

- name: Install Kubernetes components
  copy:
    remote_src: yes
    src: "/tmp/kubernetes/server/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  notify: Restart kubernetes server service

- name: Add kubernetes systemd service
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify: Restart kubernetes server service

- name: Add kubernetes apiserver environment file
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/kube-{{ item }}.service.d/10-{{ item }}.conf"
    mode: 0644
  with_items:
    - apiserver
    - controller-manager
    - scheduler
  notify: Restart kubernetes server service

- name: Add kubernetes conf file
  template:
    src: "{{ item }}"
    dest: "/etc/kubernetes/{{ item }}"
    mode: 0644
  with_items:
    - controller-manager.conf
    - scheduler.conf
    - admin.conf
  notify: Restart kubernetes server service

- name: Copy kubernetes certificate
  copy:
    src: "./roles/kubernetes/server/gencert/files/{{ item }}"
    dest: "/opt/kubernetes/tls/{{ item }}"
    mode: 0644
  with_items:
    - apiserver.crt
    - apiserver.key
    - apiserver-etcd-client.crt
    - apiserver-etcd-client.key
    - apiserver-kubelet-client.crt
    - apiserver-kubelet-client.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - front-proxy-client.crt
    - front-proxy-client.key
    - sa.key
    - sa.pub
  notify: Restart kubernetes server service

- name: Copy ca certificate
  copy:
    src: ./roles/vault/config/files/ca.crt
    dest: "/opt/kubernetes/tls/{{ item }}"
    mode: 0644
  with_items:
    - ca.crt
    - ca.key
  notify: Restart kubernetes server service

- name: Copy etcd ca certificate
  copy:
    src: ./roles/vault/config/files/ca.crt
    dest: /opt/etcd/tls/ca.crt
    mode: 0644
  notify: Restart kubernetes server service
