---
# tasks file for generate-certificate

# Generate CA certificate
- name: Generate an CA private key with the default values (4096 bits, RSA) and a passphrase
  openssl_privatekey:
    path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.pem"
    passphrase: helloworld
    cipher: auto

- name: Generate an CA Certificate Signing Request
  openssl_csr:
    path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.csr"
    privatekey_path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.pem"
    privatekey_passphrase: helloworld
    common_name: "{{ IPOOL_FQDN }}"
    country_name: "CN"
    basic_constraints: "CA:TRUE"
    email_address: "admin@radix10.me"
    locality_name: "Beijing"
    state_or_province_name: "Beijing"

- name: Generate a Self Signed CA Certificate
  openssl_certificate:
    path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.crt"
    privatekey_path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.pem"
    privatekey_passphrase: helloworld
    csr_path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.csr"
    provider: selfsigned
    ownca_create_authority_key_identifier: yes
  register: ownca_authority_key_identifier

- name: Get information on the CSR
  openssl_csr_info:
    path:  "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.csr"
  register: result

- name: Pring ownca_authority_key_identifier
  debug:
    msg: "{{ result }}"

- name: Pring ownca_authority_key_identifier
  debug:
    msg: "{{ ownca_authority_key_identifier }}"

# Generate Harbor certificate
- name: Generate an Harbor private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: "roles/openssl/generate-certificate/files/{{ HARBOR_FQDN }}.pem"

- name: Generate an Harbor Certificate Signing Request
  openssl_csr:
    path: "roles/openssl/generate-certificate/files/{{ HARBOR_FQDN }}.csr"
    privatekey_path: "roles/openssl/generate-certificate/files/{{ HARBOR_FQDN }}.pem"
    authority_cert_issuer: "DNS:{{ IPOOL_FQDN }}"
    authority_cert_serial_number: "{{ ownca_authority_key_identifier.serial_number }}"
    #authority_key_identifier: "keyid,issuer"
    basic_constraints: CA:FALSE
    key_usage: 
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
    extended_key_usage: serverAuth
    subject_alt_name: 'DNS:www.harbor.ipool.me,DNS:harbor.ipool.me'
    common_name: "{{ HARBOR_FQDN }}"
    country_name: "CN"
    email_address: "admin@radix10.me"
    locality_name: "Beijing"
    state_or_province_name: "Beijing"

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "roles/openssl/generate-certificate/files/{{ HARBOR_FQDN }}.crt"
    csr_path: "roles/openssl/generate-certificate/files/{{ HARBOR_FQDN }}.csr"
    ownca_path:  "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.crt"
    ownca_privatekey_path: "roles/openssl/generate-certificate/files/{{ IPOOL_FQDN }}.pem"
    ownca_privatekey_passphrase: helloworld
    provider: ownca
