---
# common land
name: radix10
PKI_TTL: 7200h
MAX_PKI_TTL: 21600h

# for etcd
ETCD_PACKAGE: /home/radix10/desktop/docker-downloader/downloads/etcd-v3.3.25-linux-amd64.tar.gz

# for kubernetes server
KUBERNETES_PACKAGE: /home/radix10/desktop/docker-downloader/downloads/kubernetes-server-linux-amd64.tar.gz

# for kubernetes node
KUBERNETES_NODE_PACKAGE: /home/radix10/desktop/docker-downloader/downloads/kubernetes-node-linux-amd64.tar.gz
CNI_PACKAGE: /home/radix10/desktop/docker-downloader/downloads/cni-plugins-linux-amd64-v0.8.7.tgz
PAUSE_VERSION: 3.2

# for harbor
HARBOR_FQDN: harbor.ipool.me
HARBOR_PACK: /home/radix10/Downloads/harbor.tar.gz

# for bind
FALLBACK_DNS: 114.114.114.114

# for vault
VAULT_FQDN: vault.ipool.me
VAULT_PACK: /home/radix10/downloads/vault_1.6.0_amd64.deb
VAULT_OFFLINE_INSTALL: True

# for gitlab
GITLAB_FQDN: gitlab.ipool.me

# for apt
APT_CACHE_HOST: 192.168.123.101
APT_CACHEABLE: False
