---
- name: Include vault keys
  include_vars:
    file: ./roles/vault/config/files/sys-init-result.json
    name: sys_init_result

- name: Add harbor role
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: "https://vault.ipool.me:8200/v1/pki_int/roles/{{ HARBOR_FQDN }}"
    body_format: json
    status_code: 204
    body:
      allowed_domains: "{{ HARBOR_FQDN }}"
      allow_any_name: true
      allow_subdomains: yes

- name: Generate harbor certificate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: "https://vault.ipool.me:8200/v1/pki_int/issue/{{ HARBOR_FQDN }}"
    body_format: json
    status_code: 200
    body:
      common_name: "{{ HARBOR_FQDN }}"
      ip_sans: "{{ ansible_host }}"
  register: certificate

- name: Persistent harbor certificate
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.certificate }}"
    dest: "./roles/harbor/prepare/files/{{ HARBOR_FQDN }}.crt"

- name: Persistent harbor private key
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.private_key }}"
    dest: "./roles/harbor/prepare/files/{{ HARBOR_FQDN }}.key"

