---
# tasks file for docker-ce-config
- name: Create docker cert directory
  file:
    path: "/etc/docker/certs.d/{{ HARBOR_FQDN }}"
    state: directory
    mode: '0755'
    
- name: Copy custome registry cert
  copy:
    src: "roles/openssl/generate-certificate/files/{{ item }}"
    dest: "/etc/docker/certs.d/{{ HARBOR_FQDN }}/{{item}}"
    mode: '0755'
  with_items:
  - "{{ HARBOR_FQDN }}.crt"
  - "{{ HARBOR_FQDN }}.pem"
  - "{{ IPOOL_FQDN }}.crt"

    #- name: Restart docker daemon
    #  systemd:
    #    state: restarted
    #    name: docker
