---
- name: Add etcd client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/roles/client.etcd.ipool.me
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      allowed_domains: client.etcd.ipool.me

- name: Generate etcd client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/issue/client.etcd.ipool.me
    body_format: json
    status_code: 200
    body:
      common_name: client.etcd.ipool.me
      ip_sans: "{{ ansible_host }}"
  register: certificate

- name: Persistent etcd client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: /opt/etcd/tls/client.crt
    mode: 0644

- name: Persistent etcd client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: /opt/etcd/tls/client.key
    mode: 0644
