---
- name: Create etcd cert directory
  file:
    path: /opt/etcd/tls
    state: directory
    mode: 0755

- name: Add etcd peer role
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/roles/peer.etcd.ipool.me
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      allowed_domains: peer.etcd.ipool.me

- name: Generate etcd peer certificate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/issue/peer.etcd.ipool.me
    body_format: json
    status_code: 200
    body:
      common_name: peer.etcd.ipool.me
      ip_sans: "{{ ansible_host }}"
  register: certificate

- name: Persistent etcd peer certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: /opt/etcd/tls/peer.crt
    mode: 0644

- name: Persistent etcd peer key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: /opt/etcd/tls/peer.key
    mode: 0644
