---
- name: Initializing the vault
  local_action:
    module: uri
    method: PUT
    url: https://Vault:8200/v1/sys/init
    body:
      secret_shares: 10,
      secret_threshold: 5
  register: sys-init-result
  environment:
    VAULT_ADDR: https://Vault:8200
  listen: Initializing the vault

- name: Persistent init result
  local_action:
    module: copy
    content: "{{ sys-init-result }}"
    dest: ./roles/vault/config/files/sys-init-result.json
  listen: Initializing the vault
