- name: Generate GitLab Certificate
  hosts: localhost
  become: False
  roles:
    - openssl/generate-ca-certificate
    - openssl/generate-gitlab-certificate

- name: Setup GitLab Server
  hosts: gitlab.ipool.me
  roles:
    - gitlab/server/setup
    - openssl/setup-ca-certificate
    - coredns/config

- name: Setup GitLab Runner
  hosts: runner.ipool.me
  roles:
    - gitlab/runner/setup
