---
# tasks file for raspberrypi
- name:
  apt_repository:
    repo: "{{ item }}"
    state: absent
    mode: 0644
  with_items:
  - deb http://archive.raspberrypi.org/debian/ buster main
  - deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi

- name:
  apt_repository:
    repo: "{{ item }}"
    state: present
    mode: 0644
  with_items:
  - deb http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian/ buster main non-free contrib rpi
  - deb http://mirrors.tuna.tsinghua.edu.cn/raspberrypi/ buster main ui
