---
- name: Enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kubernetes/package
    - /var/lib/kubelet
    - /etc/kubernetes/manifests

- name: Create kubelet and kube-proxy systemd service directory
  file:
    path: /etc/systemd/system/{{ item }}.service.d
    state: directory
  with_items:
    - kubelet
    - kube-proxy

- include_tasks: kube-proxy.yml
