---
- name: Enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kubernetes/package
    - /opt/kubernetes/tls
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /etc/kubernetes/manifests
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/kube-proxy.service.d

- include_tasks: kube-proxy.yml
