---
- name: Config apt cache proxy
  template:
    src: 30proxy
    dest: /etc/apt/apt.conf.d/30proxy
    mode: 0644
  when: ENABLE_APT_CACHE

- name: Config apt source mirror
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0644
