---
- name: Add kube-apiserver-etcd-client role
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/roles/client.etcd.apiserver.kubernetes.ipool.me
    body_format: json
    status_code: 204
    body:
      allowed_domains: kube-apiserver-etcd-client
      allow_any_name: true
      allow_subdomains: yes
      max_ttl: 2400h

# Generate kubernetes kube-apiserver-etcd-client certificate
- name: Generate kubernetes kube-apiserver-etcd-client certificate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/issue/client.etcd.apiserver.kubernetes.ipool.me
    body_format: json
    status_code: 200
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ExtKeyUsageClientAuth"]
      common_name: kube-apiserver-etcd-client
      max_ttl: 2400h
  register: certificate

- name: Persistent kube-apiserver-etcd-client certificate
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.certificate }}"
    dest: ./roles/kubernetes/server/gencert/files/apiserver.crt
    mode: 0644

- name: Persistent kube-apiserver-etcd-client key
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.private_key }}"
    dest: ./roles/kubernetes/server/gencert/files/apiserver.key
    mode: 0644