---
- name: Set Timezone
  timezone:
    name: Asia/Shanghai

- name: Disable Auto Update
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '1'
    replace: '0'
    backup: yes

- name: Copy self-signed certificate
  copy:
    src: ./roles/vault/config/files/ca.crt
    dest: /usr/local/share/ca-certificates/ca.crt
    mode: 0755
  notify: Setup ca certificate
