---
- name: Create Vault data directory
  file:
    path: /var/lib/vault/data
    state: directory
    mode: 0700

- name: Copy Vault config file
  copy:
    src: config.hcl
    dest: /etc/config.hcl
    mode: 0600

- name: Enable and start Etcd service
  systemd:
    name: vault
    daemon_reload: true
    state: started
    enabled: true
