---
- name: Create coredns install package directory
  file:
    path: /opt/coredns/package
    state: directory

- name: Extract coredns package
  unarchive:
    src: "{{ COREDNS_PACKAGE }}"
    dest: /opt/coredns/package
    creates: /opt/coredns/package/coredns

- name: Install coredns
  copy:
    src: /opt/coredns/package/coredns
    dest: /usr/bin/coredns
    remote_src: yes
    mode: 0755
  notify: Enable and restart coredns service

- name: Copy coredns systemd service file
  copy:
    src: coredns.service
    dest: /etc/systemd/system
    mode: 0644
  notify: Enable and restart coredns service

- name: Copy coredns config file
  copy:
    src: "{{ item }}"
    dest: /var/lib/coredns/
    mode: 0644
  with_items:
    - Corefile
    - ipool.me.db
  notify: Enable and restart coredns service

- name: Stop systemd-resolved service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
