---
- name: Create coredns temporary directory
  file:
    path: /tmp/coredns
    state: directory

- name: Extract coredns package
  unarchive:
    src: "{{ COREDNS_PACKAGE }}"
    dest: /tmp/coredns
    creates: /tmp/coredns/coredns

- name: Install coredns
  copy:
    src: /tmp/coredns/coredns
    dest: /usr/bin/coredns
    remote_src: yes
    mode: 0755
  notify: Enable and restart coredns service

- name: Copy systemd unit
  copy:
    src: coredns.service
    dest: /etc/systemd/system
    mode: 0644
  notify: Enable and restart coredns service

- name: Copy config file
  copy:
    src: "{{ item }}"
    dest: /var/lib/coredns/
    mode: 0644
  with_items:
    - Corefile
    - ipool.me.db
  notify: Enable and restart coredns service

- name: Stop systemd-resolved service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
