---
- name: Generate random token id and token secret
  set_fact:
    token_id: "{{ lookup('password', '/dev/null length=6 chars=ascii_letters') | lower }}"
    token_secret: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') | lower }}"

- name: Copy cluster role binding yml for tls bootstraping
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - auto-approve-csrs-for-group.yml
    - auto-approve-renewals-for-nodes.yml
    - create-csrs-for-bootstrapping.yml
    - "{{ FLANNEL_MANIFESTS_FILE }}"

- name: Initializing cluster role binding
  shell:
    cmd: "kubectl apply -f /root/{{ item }}"
    chdir: "/root/"
  with_items:
    - auto-approve-csrs-for-group.yml
    - auto-approve-renewals-for-nodes.yml
    - create-csrs-for-bootstrapping.yml
    - flannel.yml

- name: Copy token yml
  template:
    src: token.yml
    dest: /root/token.yml
    mode: 0644

- name: Apply token to kubernetes
  shell:
    cmd: kubectl apply -f /root/token.yml

- name: Generate bootstrap-kubelet.conf
  become: no
  local_action:
    module: template
    src: bootstrap-kubelet.yml
    dest: roles/kubernetes/server/config/files/bootstrap-kubelet.yml
    mode: 0644
