---
- name: Copy cluster role binding yml for tls bootstraping
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - auto-approve-csrs-for-group.yml
    - auto-approve-renewals-for-nodes.yml
    - create-csrs-for-bootstrapping.yml

- name: Initializing cluster role binding
  shell:
    cmd: "kubectl apply -f /root/{{ item }}"
  with_items:
    - auto-approve-csrs-for-group.yml
    - auto-approve-renewals-for-nodes.yml
    - create-csrs-for-bootstrapping.yml

- name: Copy token yml
  template:
    src: token.yml
    dest: /root/token.yml
    mode: 0644

- name: Apply token to kubernetes
  shell:
    cmd: kubectl apply -f /root/token.yml

- name: Generate bootstrap-kubelet.conf
  become: no
  local_action:
    module: template
    src: bootstrap-kubelet.yml
    dest: roles/kubernetes/server/config/files/bootstrap-kubelet.yml
    mode: 0644
