---
- name: Include keys as variable
  include_vars:
    file: ./roles/vault/config/files/sys-init-result.json
    name: sys_init_result

- name: Add gitlab role
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/roles/gitlab.ipool.me
    body_format: json
    status_code: 204
    body:
      allowed_domains: gitlab.ipool.me
      allow_any_name: true
      allow_subdomains: yes
      max_ttl: 2400h

- name: Generate gitlab certificate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/issue/gitlab.ipool.me
    body_format: json
    status_code: 200
    body:
      common_name: gitlab.ipool.me
  register: certificate

- name: Persistent gitlab certificate
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.certificate }}"
    dest: "./roles/gitlab/gencert/{{ GITLAB_FQDN }}.crt"
    mode: 0644

- name: Persistent gitlab key
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.private_key }}"
    dest: "./roles/gitlab/gencert/{{ GITLAB_FQDN }}.key"
    mode: 0644

