---
# tasks file for setup
- name: Download CoreDNS
  get_url:
    url: https://cdn.radix10.cn/coredns?a=10086
    dest: /usr/bin/coredns
    mode: 0755

- name: Copy systemd unit
  copy:
    src: "coredns.service"
    dest: "/etc/systemd/system"
    mode: '0644'

- name: Copy config file
  copy:
    src: "{{ item }}"
    dest: "/var/lib/coredns/"
    mode: '0644'
  with_items:
  - Corefile
  - ipool.db

- name: Stop systemd-resolved service
  systemd:
    name: "systemd-resolved"
    state: stopped
    enabled: true

- name: Enable and start coredns service
  systemd:
    name: "coredns"
    state: started
    enabled: true
