---
# tasks file for generate-kubernetes-server-certificate
- name: Generate an Harbor private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: "roles/openssl/generate-kubernetes-kubelet-certificate/files/{{ K8S_API_SERVER_FQDN }}.key"

- name: Generate an Kubernetes API Server Certificate Signing Request
  openssl_csr:
    path: "roles/openssl/generate-kubernetes-kubelet-certificate/files/{{ K8S_API_SERVER_FQDN }}.csr"
    privatekey_path: "roles/openssl/generate-kubernetes-kubelet-certificate/files/{{ K8S_API_SERVER_FQDN }}.key"
    basic_constraints: CA:FALSE
    key_usage:
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
    extended_key_usage: serverAuth
    subject_alt_name: 'DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:k8s-master,IP:127.0.0.1,IP:127.0.0.1'
    common_name: "192.168.123.100"
    country_name: "CN"
    email_address: "admin@radix10.me"
    locality_name: "Beijing"
    state_or_province_name: "Beijing"

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "roles/openssl/generate-kubernetes-kubelet-certificate/files/{{ K8S_API_SERVER_FQDN }}.crt"
    csr_path: "roles/openssl/generate-kubernetes-kubelet-certificate/files/{{ K8S_API_SERVER_FQDN }}.csr"
    ownca_path:  "roles/openssl/generate-ca-certificate/files/{{ IPOOL_FQDN }}.crt"
    ownca_privatekey_path: "roles/openssl/generate-ca-certificate/files/{{ IPOOL_FQDN }}.key"
    ownca_privatekey_passphrase: helloworld
    provider: ownca
