---
- name: Extract kubernetes package
  unarchive:
    src: "{{ KUBERNETES_NODE_PACKAGE }}"
    dest: /opt/kubernetes/package
    creates: /opt/kubernetes/package/node
    extra_opts: [ "--strip-components=1" ]

- name: Install kubelet and kube-proxy
  copy:
    src: "/opt/kubernetes/package/node/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
    - kubelet
    - kube-proxy

- name: Add kubernetes node service
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: Add kubernetes node service configuration
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}.d/10-{{ item }}"
    mode: 0644
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: Copy kubelet config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: config.yaml, dest: /var/lib/kubelet/config.yaml }
    - { src: flags.env, dest: /var/lib/kubelet/kubeadm-flags.env}

- name: Copy kube-proxy config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: config.conf, dest: /var/lib/kube-proxy/config.conf }
    - { src: kubeconfig.conf, dest: /var/lib/kube-proxy/kubeconfig.conf }

- name: Copy bootstrap-kubelet.conf
  copy:
    src: ./roles/kubernetes/server/initialize/files/bootstrap-kubelet.yml
    dest: /etc/kubernetes/bootstrap-kubelet.conf

- name: Pull Pause docker image
  docker_image:
    name: "registry.aliyuncs.com/google_containers/pause:{{ PAUSE_VERSION }}"
    repository: "k8s.gcr.io/pause:{{ PAUSE_VERSION }}"
    source: pull
