---
# tasks file for harbor-setup
- name: Create harbor directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  with_items:
  - /opt/harbor/certificate
  - /opt/harbor/data

- name: Extract harbor offline package
  unarchive:
    src: "{{ HARBOR_PACK }}"
    dest: /opt/harbor
    extra_opts: [--strip-components=1]
    creates: /opt/harbor/install.sh

- name: Copy Harbor certificate
  copy:
    src: "roles/openssl/generate-harbor-certificate/files/{{ item }}"
    dest: "/opt/harbor/certificate/{{ item }}"
    mode: 0755
  with_items:
    - harbor.ipool.me.crt
    - harbor.ipool.me.key

- name: Copy generate harbor yml script
  copy:
    src: generate-harbor-yml.py
    dest: /opt/harbor/generate-harbor-yml.py
    mode: 0755

- name: Generate harbor.yml
  shell: ./generate-harbor-yml.py
  args:
    chdir: /opt/harbor

- name: Install harbor
  shell: ./install.sh
  args:
    chdir: /opt/harbor/
