- name: Create kubernetes temporary directory
  file:
    path: '/tmp/kubernetes'
    state: directory

- name: Extract kubernetes package
  unarchive:
    src: /home/radix10/desktop/my-server-playbook/roles/kubernetes/templates/kubernetes-server-linux-amd64.tar.gz
    dest: '/tmp/kubernetes'
    creates: '/tmp/kubernetes/server'
    extra_opts: [--strip-components=1]


- name: Install Kubernetes worker components
  copy:
    src: "/tmp/kubernetes/server/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: true
    mode: '0755'
  with_items:
  - kubelet
  - kube-proxy


- name: Add Kubernetes worker systemd service
  copy: 
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/{{ item }}"
    mode: '0644'
  with_items:
  - kubelet.service
  - kube-proxy.service


- name: Create kubernetes config directory
  file:
    path: "/etc/kubernetes"
    state: directory
    mode: '0755'

- name: Add kubernetes worker environment file
  copy: 
    src: "{{ item }}"
    dest: "/etc/kubernetes"
    mode: '0644'
  with_items:
  - kubelet
  - kube-proxy
  - kubeconfig


- name: Systemd daemon reload
  systemd:
    daemon_reload: true
- name: Enable and start kubernetes apiserver service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - kubelet
  - kube-proxy


- name: Pull pause docker image
  docker_image:
    name: registry.aliyuncs.com/google_containers/pause:3.2
    repository: k8s.gcr.io/pause:3.2
    source: pull

- name: Create kubelet directory
  file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
