---
# tasks file for setup
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
    mode: 0644

- name: Install Vault
  apt:
    update_cache: yes
    name:
    - vault

- name: Create vault data directory
  file:
    path: /opt/vault/data
    state: directory
    mode: 0700

- name: Copy Vault config file
  copy:
    src: config.hcl
    dest: /opt/vault/config.hcl
    mode: 0600

