---
# tasks file for harbor-setup
#- name: Create harbor directory
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0775'
#  with_items:
#  - /opt/harbor/certificate
#  - /opt/harbor/data
#
#- name: Extract harbor offline package
#  unarchive:
#    src: harbor-offline-installer-v2.0.2.tgz
#    dest: /opt/harbor
#    extra_opts: [--strip-components=1]
#    creates: /opt/harbor/install.sh
#
#- name: Copy generate certificate script
#  copy:
#    src: generate-certificate.sh
#    dest: /opt/harbor/certificate/generate-certificate.sh
#    mode: 0755
#
#- name: Generate certificate
#  shell: ./generate-certificate.sh
#  args:
#    chdir: /opt/harbor/certificate/
#
#- name: Copy generate harbor yml script
#  copy:
#    src: generate-harbor-yml.py
#    dest: /opt/harbor/generate-harbor-yml.py
#    mode: 0755
#

- name: Download cert to local
  fetch:
    src: "/opt/harbor/certificate/{{ item }}"
    dest: roles/harbor-setup/files
  with_items:
    - ca.crt
    - ca.key
    - ca.srl
    - harbor.ipool.me.cert
    - harbor.ipool.me.crt
    - harbor.ipool.me.csr
    - harbor.ipool.me.key
    - v3.ext

#- name: Generate harbor.yml
#  shell: ./generate-harbor-yml.py
#  args:
#    chdir: /opt/harbor
#
#- name: Install harbor
#  shell: ./install.sh
#  args:
#    chdir: /opt/harbor/
#
#- name: Fetch certificate
#  fetch:
#    src: "/opt/harbor/{item}"
#    dest: /tmp/
