---
# tasks file for setup-gitlab-server
- name: Install GitLab dependencies
  apt:
    update_cache: yes
    name:
    - postfix
    - apt-transport-https

- name: Enable and start postfix service
  systemd:
    name: postfix
    state: started
    enabled: true

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.gitlab.com/gpg.key
    state: present

- name:
  apt_repository:
    repo: deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu focal main
    state: present
    mode: 0644

- name: Create certificate directory
  file:
    path: "/etc/gitlab/ssl"
    state: directory
    mode: '0755'

- name: Copy custome registry cert
  copy:
    src: "roles/openssl/generate-gitlab-certificate/files/{{ item }}"
    dest: "/etc/gitlab/ssl/{{item}}"
    mode: '0755'
  with_items:
  - "{{ GITLAB_FQDN }}.crt"
  - "{{ GITLAB_FQDN }}.key"

- name: Install GitLab CE
  apt:
    update_cache: yes
    name:
    - gitlab-ce
  environment:
    EXTERNAL_URL: "{{ EXTERNAL_URL }}"
