---
- name: Notify test
  shell: ls
  notify: Initializing the vault

- name: Update vault ip address
  become: false
  local_action:
    module: replace
    path: ./roles/coredns/config/defaults/main.yml
    regexp: 'VAULT_IP:.*'
    replace: "VAULT_IP: {{ ansible_facts.enp0s8.ipv4.address }}"

- name: Add default vault address to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR='https://Vault:8200'
    state: present

- name: Enable vault service
  systemd:
    name: vault
    daemon_reload: true
    enabled: true
  notify: Initializing the vault

- name: Start vault service
  systemd:
    name: vault
    state: started
