---
- name: Copy vault certificate
  copy:
    remote_src: true
    src: /opt/vault/tls/tls.crt
    dest: /usr/local/share/ca-certificates/vault-ca.crt
    mode: 0755
  notify: Update ca certificate

- name: Add Vault to hosts
  lineinfile:
    dest: /etc/hosts
    line: 127.0.0.1 Vault Vault
    state: present

- name: Add default vault address to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR='https://Vault:8200'
    state: present

- name: Enable vault service
  systemd:
    name: vault
    daemon_reload: true
    enabled: true
  notify: Initializing the vault

- name: Start vault service
  systemd:
    name: vault
    state: started
