---
- name: Add Vault to hosts
  lineinfile:
    dest: /etc/hosts
    line: 127.0.0.1 Vault Vault
    state: present

- name: Add default vault address to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR='https://Vault:8200'
    state: present

- name: Enable vault service
  systemd:
    name: vault
    daemon_reload: true
    enabled: true
#  notify: Initializing the vault

- name: Start vault service
  systemd:
    name: vault
    state: started

- name: Fetch vault certificate
  fetch:
    src: "/opt/vault/tls/{{ item }}"
    dest: "./roles/common/config/files/{{ item }}"
    flat: true
  with_items:
    - tls.crt
    - tls.key
