#cloud-config
hostname: gitlab
timezone: Asia/Shanghai
users:
  - name: radix10
    shell: /bin/bash
    passwd: $6$faskldhgln$iMMPXNPUVeUE7CkGwdEE4ETOtWDRZ6Qejho5JvfC8lLSqTrDiBRT9uEzRhaQBzcBb8qekG7c/aKjH9wcVmTai/
    lock_passwd: false
    sudo: ALL=(ALL) ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD4NDKZFS+8SP8tTRAqGpnr1Y6k/YkJJ7D6KD5AWIe7B5Q6AiExEiwy9r2iKeGiWBCl4UaEyJQD2eDBiWQ/ujYtjz6+ORJZaSksNaftWtnwgWBKEq91x4F1PrpAoF8FTA7lE+CufySU9QHypYFPy5NX9u/7lujfpDHhXTeMKkARPtIuC+oCgp01Z/KraLiBepTdv7/+KdNVEBkQwOSvZyOOTjHnRIdCkXs6oPi9ocn65d1SZDBBeXcNOtHZUrXTX7lIM1yEAhz/DbhOK6WdgbFfCexjBuyyzADi5JFv3sJqKDc+U4j9TMtX29LXipVtf0J0zVPgGeKVOWn57qmbRmFm2F1fTKmGycsujdDSrwpiVC/A+NFBxIMDGVwA8vmdif38NqMj0o/NMp8WZH3IYU35KeAMVDiYZDACEtk2CWN/cceUByoihYbkPDm6AMK4dDJ0YQ1kn4Hq0VVo5RLhxLB3HenGV+AX/BHFoQZfq9x8kGZE73ktamNTB30UWrsMg8c= radix10@x1
