---
- name: Add default vault address to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR='https://vault.ipool.me:8200'
    state: present

- name: Enable vault service
  systemd:
    name: vault
    daemon_reload: yes
    enabled: yes
  notify: Initializing the vault

- name: Start vault service
  systemd:
    name: vault
    state: started
