- name: Install kubelet
  get_url:
    url: /tmp/kubernetes/node/bin/kubelet
    dest: /usr/bin/kubelet
    mode: 0755

- name: Add kubelet systemd service
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system/kubelet.service
    mode: 0644

- name: Create kubernetes config directory
  file:
    path: "/etc/kubernetes"
    state: directory
    mode: '0755'

- name: Add kubernetes worker environment file
  copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes"
    mode: '0644'
  with_items:
  - kubelet
  - kubelet.conf
  - kube-proxy
  - kubeconfig


- name: Enable and start kubernetes apiserver service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
  - kubelet
  - kube-proxy


- name: Pull Pause docker image
  docker_image:
    name: "registry.aliyuncs.com/google_containers/pause:{{ PAUSE_VERSION }}"
    repository: "k8s.gcr.io/pause:{{ PAUSE_VERSION }}"
    source: pull

- name: Pull ETCD docker image
  docker_image:
    name: "quay.io/coreos/etcd:{{ ETCD_VERSION }}"
    repository: "k8s.gcr.io/etcd:{{ ETCD_VERSION }}"
    source: pull

- name: Pull CoreDNS docker image
  docker_image:
    name: "registry.aliyuncs.com/google_containers/coredns:{{ COREDNS_VERSION }}"
    repository: "k8s.gcr.io/coredns:{{ COREDNS_VERSION }}"
    source: pull

- name: Pull Kubernetes docker image
  docker_image:
    name: "registry.aliyuncs.com/google_containers/{{ item }}:{{ KUBERNETES_VERSION }}"
    repository: "k8s.gcr.io/{{ item }}:{{ KUBERNETES_VERSION }}"
    source: pull
	with_items:
	- kube-apiserver
	- kube-controller-manager
	- kube-scheduler
	- kube-proxy

- name: Create kubelet directory
  file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'
