- name: Install Docker CE and Docker Compose
  apt:
    update_cache: yes
    name:
    - docker-compose

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: true
