---
- name: Check Vault CA key stat
  become: no
  local_action:
    module: stat
    path: "./roles/vault/setup/files/{{ VAULT_FQDN }}.key"
  register: vault_ca_key

- name: Generate an CA private key with the default values (4096 bits, RSA) and a passphrase
  local_action:
    module: openssl_privatekey
    path: "./roles/vault/setup/files/{{ VAULT_FQDN }}.key"
    cipher: aes256
    passphrase:
  when: not vault_ca_key.stat.exists

- name: Generate an CA Certificate Signing Request
  local_action:
    module: openssl_csr
    path: "./roles/vault/setup/files/{{ VAULT_FQDN }}.csr"
    privatekey_path: "roles/vault/setup/files/{{ VAULT_FQDN }}.key"
    common_name: "{{ VAULT_FQDN }}"
    basic_constraints: 'CA:TRUE'
    email_address: "admin@eastack.me"
    country_name: "CN"
    state_or_province_name: "ShanDong"
    locality_name: "JiNan"
  when: not vault_ca_key.stat.exists

- name: Generate a Self Signed CA Certificate
  local_action:
    module: openssl_certificate
    privatekey_path: "roles/vault/setup/files/{{ VAULT_FQDN }}.key"
    csr_path: "roles/vault/setup/files/{{ VAULT_FQDN }}.csr"
    path: "roles/vault/setup/files/{{ VAULT_FQDN }}.crt"
    provider: selfsigned
  when: not vault_ca_key.stat.exists
