---
- name: Add apt signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com buster main
    state: present
    mode: 0644

- name: Install Vault
  apt:
    update_cache: true
    name:
    - vault

- name: Fetch vault certificate
  fetch:
    src: "/opt/vault/tls/{{ item }}"
    dest: "./roles/vault/setup/files/{{ item }}"
    flat: true
  with_items:
    - tls.crt
    - tls.key
