---
- name: Online install vault
  include_tasks:
    file: offline-install.yaml
  when: VAULT_OFFLINE_INSTALL

- name: Offline install vault
  include_tasks:
    file: online-install.yaml
  when: not VAULT_OFFLINE_INSTALL

- include_tasks:
    file: generate-ca-key.yaml
    apply:
      become: no

- name: Copy selfsigned ca certificate
  copy:
    src: "roles/vault/setup/files/{{ item.src }}"
    dest: "/opt/vault/tls/{{ item.dest }}"
  with_items:
    - { src: "{{ VAULT_FQDN }}.key", dest: tls.key }
    - { src: "{{ VAULT_FQDN }}.crt", dest: tls.crt }
