---
- name: Config DNS
  replace:
    path: /etc/systemd/resolved.conf
    regexp: '#DNS='
    replace: "DNS={{ hostvars.bind9.ansible_host }}"
    backup: yes

- name: Config Fallback DNS
  replace:
    path: /etc/systemd/resolved.conf
    regexp: '#FallbackDNS='
    replace: "FallbackDNS={{ FALLBACK_DNS }}"
    backup: yes

- name: Restart systemd-resolved service
  systemd:
    name: systemd-resolved
    state: restarted