---
- name: Add admin role
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/roles/admin.kubernetes.ipool.me
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      organization: system:masters
      common_name: kubernetes-admin
      allow_any_name: true

- name: Generate admin certificate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/issue/admin.kubernetes.ipool.me
    body_format: json
    status_code: 200
    body:
      common_name: kubernetes-admin
  register: admin_certificate

- name: Persistent admin certificate
  become: no
  local_action:
    module: copy
    content: "{{ admin_certificate.json.data.certificate }}"
    dest: ./roles/kubernetes/server/prepare/files/admin.crt
    mode: 0644

- name: Persistent admin key
  become: no
  local_action:
    module: copy
    content: "{{ admin_certificate.json.data.private_key }}"
    dest: ./roles/kubernetes/server/prepare/files/admin.key
    mode: 0644
