---
- name: Generate sa RSA private key
  become: no
  local_action:
    module: shell
    cmd: openssl genrsa -out sa.key 2048
    args:
      chdir: ./roles/kubernetes/server/prepare/files

- name: Generate sa RSA public key
  become: no
  local_action:
    module: shell
    cmd: openssl rsa -in sa.key -pubout -out sa.pub
    args:
      chdir: ./roles/kubernetes/server/prepare/files
