---
- name: Create etcd directory
  file:
    path: /tmp/etcd
    state: directory

- name: Extract etcd package
  unarchive:
    src: "{{ ETCD_PACKAGE }}"
    dest: /tmp/etcd
    extra_opts: [--strip-components=1]
    creates: /tmp/etcd/etcdctl

- name: Copy etcdctl to /usr/bin
  copy:
    src: "/tmp/etcd/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: true
    mode: 0755
  with_items:
  - etcd
  - etcdctl
	notify: Enable and restart etcd service

- name: Add etcd systemd service
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0644
	notify: Enable and restart etcd service

- name: Create etcd work directory
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755
