---
# tasks file for generate-harbor-certificate
- name: Generate an Harbor private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: "roles/openssl/generate-harbor-certificate/files/{{ HARBOR_FQDN }}.key"

- name: Generate an Harbor Certificate Signing Request
  openssl_csr:
    path: "roles/openssl/generate-harbor-certificate/files/{{ HARBOR_FQDN }}.csr"
    privatekey_path: "roles/openssl/generate-harbor-certificate/files/{{ HARBOR_FQDN }}.key"
    basic_constraints: CA:FALSE
    key_usage: 
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
    extended_key_usage: serverAuth
    subject_alt_name: 'DNS:www.harbor.ipool.me,DNS:harbor.ipool.me'
    common_name: "{{ HARBOR_FQDN }}"
    country_name: "CN"
    email_address: "admin@radix10.me"
    locality_name: "Beijing"
    state_or_province_name: "Beijing"

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "roles/openssl/generate-harbor-certificate/files/{{ HARBOR_FQDN }}.crt"
    csr_path: "roles/openssl/generate-harbor-certificate/files/{{ HARBOR_FQDN }}.csr"
    ownca_path:  "roles/openssl/generate-ca-certificate/files/{{ IPOOL_FQDN }}.crt"
    ownca_privatekey_path: "roles/openssl/generate-ca-certificate/files/{{ IPOOL_FQDN }}.key"
    ownca_privatekey_passphrase: helloworld
    provider: ownca
