---
- name: Copy CA certificate
  copy:
    src: "roles/vault/setup/files/{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item }}"
  with_items:
    - "{{ VAULT_FQDN }}.crt"
    - "{{ VAULT_FQDN }}.key"
  notify: Update CA certificate
