---
- name: Install bind
  apt:
    update_cache: yes
    name:
      - bind9

- name: Update dns config
  template:
    src: "{{ item }}"
    dest: "/etc/bind/{{ item }}"
    mode: 0644
  with_items:
    - db.ipool.me
    - named.conf.local
  notify: Enable and restart bind service

- name: Stop and disable systemd-resolved service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Change /etc/resolv.conf
  replace:
    path: /etc/resolv.conf
    regexp: 127.0.0.53
    replace: 127.0.0.1
    backup: yes
