---
- name: Install bind
  apt:
    update_cache: yes
    name:
      - bind

- name: Update dns config
  template:
    src: "{{ item }}"
    dest: "/etc/bind/{{ item }}"
    mode: 0644
  notify: Enable and restart bind service
  with_items:
    - db.ipool.me
    - named.conf.local

- name: Stop and disable systemd-resolved service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
