---
- name: Waits vault service started
  wait_for:
    host: localhost
    port: 8200
  listen: Initializing the vault

- name: Init the vault
  uri:
    method: PUT
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/init
    body_format: json
    body:
      secret_shares: 10
      secret_threshold: 5
  register: result
  listen: Initializing the vault

- name: Persistent init result
  become: no
  local_action:
    module: copy
    content: "{{ result.json }}"
    dest: ./roles/vault/config/files/vault-init-result.json
  listen: Initializing the vault

# Unseal
- name: Include Vault keys
  include_vars:
    file: ./roles/vault/config/files/vault-init-result.json
    name: vault_init_result
  listen: Initializing the vault

- name: Unseal vault
  uri:
    method: PUT
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/unseal
    body_format: json
    body:
      key: "{{ item }}"
  with_items: "{{ vault_init_result['keys'] }}"
  listen: Initializing the vault

# Mount PKI secret engine
- name: Mount PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/mounts/pki
    body_format: json
    status_code: 204
    body:
      type: pki
  listen: Initializing the vault

- name: Tune PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/mounts/pki/tune
    body_format: json
    status_code: 204
    body:
      description: Root certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ MAX_PKI_TTL }}"
  listen: Initializing the vault

# Submit CA certificate
- name: Submit CA certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/pki/config/ca
    body_format: json
    status_code: 204
    body:
      pem_bundle: "{{ lookup('file', './roles/vault/setup/files/{{ VAULT_FQDN }}.key') + '\n' +  lookup('file', './roles/vault/setup/files/{{ VAULT_FQDN }}.crt') }}"
  listen: Initializing the vault

# Mount intermediate ca
- name: Mount PKI intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/mounts/pki_int
    body_format: json
    status_code: 204
    body:
      type: pki
  listen: Initializing the vault

- name: Tune PKI intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    validate_certs: no
    url: https://vault.ipool.me:8200/v1/sys/mounts/pki_int/tune
    body_format: json
    status_code: 204
    body:
      description: Intermediate certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ PKI_TTL }}"
  listen: Initializing the vault

# Generate intermediate CA
- name: Generate intermediate CA csr
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/intermediate/generate/exported
    body_format: json
    body:
      common_name: ipool.me
  register: intermediate_ca_csr
  listen: Initializing the vault

- name: Persistent peer intermediate CA CSR result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_csr.json.data.csr }}"
    dest: ./roles/vault/config/files/vault_int_ca.csr
  listen: Initializing the vault

- name: Persistent intermediate CA private key result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_csr.json.data.private_key }}"
    dest: ./roles/vault/config/files/vault_int_ca.key
  listen: Initializing the vault

- name: Sign intermediate CA
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki/root/sign-intermediate
    body_format: json
    body:
      csr: "{{ lookup('file', './roles/vault/config/files/vault_int_ca.csr') }}"
  register: intermediate_ca_crt
  listen: Initializing the vault

- name: Persistent intermediate CA certificate result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_crt.json.data.certificate }}"
    dest: ./roles/vault/config/files/vault_int_ca.crt
  listen: Initializing the vault

- name: Set sign intermediate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: https://vault.ipool.me:8200/v1/pki_int/intermediate/set-signed
    body_format: json
    status_code: 204
    body:
      certificate: "{{ lookup('file', './roles/vault/config/files/vault_int_ca.crt') }}"
  listen: Initializing the vault
