---
- name: Initializing the vault
  uri:
    method: PUT
    validate_certs: no
    url: https://Vault:8200/v1/sys/init
    body_format: json
    body:
      secret_shares: 10
      secret_threshold: 5
  register: result
  listen: Initializing the vault

- name: Persistent init result
  become: no
  local_action:
    module: copy
    content: "{{ result.json }}"
    dest: ./roles/vault/config/files/sys-init-result.json
  listen: Initializing the vault

# Unseal
- name: Include vault keys
  include_vars:
    file: ./roles/vault/config/files/sys-init-result.json
    name: sys_init_result
  listen: Initializing the vault

- name: Unseal vault
  uri:
    method: PUT
    validate_certs: no
    url: https://Vault:8200/v1/sys/unseal
    body_format: json
    body:
      key: "{{ item }}"
  with_items: "{{ sys_init_result['keys'] }}"
  listen: Initializing the vault

# Mount pki secret engine
- name: Mount pki secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    validate_certs: no
    url: https://Vault:8200/v1/sys/mounts/pki
    body_format: json
    status_code: 204
    body:
      type: pki
  listen: Initializing the vault

- name: Tune pki secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    validate_certs: no
    url: https://Vault:8200/v1/sys/mounts/pki/tune
    body_format: json
    status_code: 204
    body:
      description: Root certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ MAX_PKI_TTL }}"
  listen: Initializing the vault

# Submit ca certificate
- name: Submit ca certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    validate_certs: no
    url: https://Vault:8200/v1/pki/config/ca
    body_format: json
    status_code: 204
    body:
      pem_bundle: "{{ lookup('file', './roles/vault/setup/files/tls.key') + '\n' +  lookup('file', './roles/vault/setup/files/tls.crt') }}"
  listen: Initializing the vault

# Mount intermediate ca
- name: Mount pki intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    validate_certs: no
    url: https://Vault:8200/v1/sys/mounts/pki_int
    body_format: json
    status_code: 204
    body:
      type: pki
  listen: Initializing the vault

- name: Tune pki intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    validate_certs: no
    url: https://Vault:8200/v1/sys/mounts/pki_int/tune
    body_format: json
    status_code: 204
    body:
      description: Intermediate certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ PKI_TTL }}"
  listen: Initializing the vault

# Generate intermediate ca
- name: Generate intermediate ca csr
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/intermediate/generate/exported
    body_format: json
    body:
      common_name: ipool.me
  register: intermediate_ca_csr
  listen: Initializing the vault

- name: Persistent peer intermediate ca csr result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_csr.json.data.csr }}"
    dest: ./roles/vault/config/files/ca.csr
  listen: Initializing the vault

- name: Persistent intermediate ca private key result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_csr.json.data.private_key }}"
    dest: ./roles/vault/config/files/ca.key
  listen: Initializing the vault

- name: Sign intermediate ca
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki/root/sign-intermediate
    body_format: json
    body:
      csr: "{{ lookup('file', './roles/vault/config/files/ca.csr') }}"
  register: intermediate_ca_crt
  listen: Initializing the vault

- name: Persistent intermediate ca certificate result
  become: no
  local_action:
    module: copy
    content: "{{ intermediate_ca_crt.json.data.certificate }}"
    dest: ./roles/vault/config/files/ca.crt
  listen: Initializing the vault

- name: Set sign intermediate
  uri:
    method: POST
    validate_certs: no
    headers:
      X-Vault-Token: "{{ sys_init_result['root_token'] }}"
    url: https://Vault:8200/v1/pki_int/intermediate/set-signed
    body_format: json
    status_code: 204
    body:
      certificate: "{{ lookup('file', './roles/vault/config/files/ca.crt') }}"
  listen: Initializing the vault
