---
- name: Install docker-ce and docker-compose
  apt:
    update_cache: yes
    name:
    - docker-compose

- name: Create docker cert directory
  file:
    path: "/etc/docker/certs.d/{{ HARBOR_FQDN }}"
    state: directory
    mode: 0644

- name: Copy ca certificate
  copy:
    src: "{{ item.src }}"
    dest: "/etc/docker/certs.d/{{ HARBOR_FQDN }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: ca.crt , dest: ca.crt }
    - { src: harbor.ipool.me.crt , dest: harbor.ipool.me.crt }
    - { src: harbor.ipool.me.key , dest: harbor.ipool.me.key }
  notify: Restart docker service

- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: Restart docker service
