- name: Update DNS record
  become: yes
  hosts: bind
  roles:
    - bind/config

- name: Initialize etcd cluster
  become: yes
  hosts: etcd
  roles:
    - common/config/timezone
    - common/config/update
    - common/config/dns
    - common/config/apt
    - common/config/ca
    - vault/unseal
    - etcd/prepare
    - etcd/setup
