- name: Update DNS record
  become: yes
  hosts: bind
  roles:
    - bind/config

- name: Initialize gitlab ce
  become: yes
  hosts: gitlab
  roles:
    - common/config/timezone
    - common/config/update
    - common/config/dns
    - common/config/apt
    - common/config/ca
    - gitlab/server/prepare
    - gitlab/server/setup
