- name: Initialize kubernetes server
  become: yes
  hosts: kubernetes-server
  roles:
    - common/config/timezone
    - common/config/update
    - common/config/dns
    - common/config/apt
    - common/config/ca
    - vault/unseal
    - kubernetes/server/prepare
    - kubernetes/server/setup
