- name: Initialize vault
  become: yes
  hosts: vault
  roles:
    - common/config/timezone
    - common/config/update
    - common/config/dns
    - common/config/apt
    - vault/setup
    - common/config/ca
    - vault/config

- name: Update dns record
  become: yes
  hosts: bind9
  roles:
    - bind9/setup
